Repository RebeccaTevaearai/AMT, pull requests merged in 2022-01, with the labels that each got.

#85 Release test2
  .github/workflows/release.yml
Labels: patch

#86 Release test3
  .github/workflows/release.yml
Labels: patch

#87 Release test4
  .github/workflows/release.yml
Labels: patch

#92 Patch corr error cart
  app/src/main/java/service/CartQueries.java
Labels: patch

#94 corr bug affichage
  .github/workflows/AWS-manual-deploy-main.yml
  .github/workflows/AWS-manual-deploy.yml
  .github/workflows/release.yml
  app/pom.xml
  app/src/main/webapp/WEB-INF/web.xml
  app/src/main/webapp/css/ie6.css
  app/src/main/webapp/css/images/body.gif
  app/src/main/webapp/css/images/bul.gif
  app/src/main/webapp/css/images/cart-link.gif
  app/src/main/webapp/css/images/cat.gif
  app/src/main/webapp/css/images/h2-arr.gif
  app/src/main/webapp/css/images/header.gif
  app/src/main/webapp/css/images/ico1.gif
  app/src/main/webapp/css/images/ico2.gif
  app/src/main/webapp/css/images/ico3.gif
  app/src/main/webapp/css/images/ico4.gif
  app/src/main/webapp/css/images/info.png
  app/src/main/webapp/css/images/next.gif
  app/src/main/webapp/css/images/prev.gif
  app/src/main/webapp/js/jquery-1.4.1.min.js
  app/src/main/webapp/js/jquery-func.js
  app/src/main/webapp/js/jquery.jcarousel.pack.js
  app/src/test/java/service/ArticleQueriesTest.java
  app/src/test/java/service/CartServiceTest.java
  app/src/test/java/service/DatabaseConnectionTest.java
  images/Feature-branches.svg
  images/MCD.png
Labels: patch

#99 Test workflow
  app/src/main/webapp/jsps/testPage.jsp
Labels: patch

#110 admin panel
  .github/workflows/javadoc-pages.yml
  .github/workflows/release.yml
  README.md
  app/pom.xml
  app/src/main/java/controller/AccountController.java
  app/src/main/java/controller/AdminCategoriesController.java
  app/src/main/java/controller/AdminCategoryDeleteController.java
  app/src/main/java/controller/AdminCatergoryController.java
  app/src/main/java/controller/ArticleCategoryController.java
  app/src/main/java/controller/ArticleController.java
  app/src/main/java/controller/ArticleDetailedController.java
  app/src/main/java/controller/ArticleManagementController.java
  app/src/main/java/controller/CartController.java
  app/src/main/java/controller/CheckoutController.java
  app/src/main/java/controller/LoginController.java
  app/src/main/java/controller/LoginPageController.java
  app/src/main/java/controller/LogoutController.java
  app/src/main/java/controller/ManagementController.java
  app/src/main/java/controller/RegisterController.java
  app/src/main/java/controller/UpdateCartController.java
  app/src/main/java/controller/articleImageController.java
  app/src/main/java/service/AccountQueries.java
  app/src/main/java/service/AddArticleService.java
  app/src/main/java/service/ArticleQueries.java
  app/src/main/java/service/AuthorizationService.java
  app/src/main/java/service/CartQueries.java
  app/src/main/java/service/CategoryQueries.java
  app/src/main/java/service/DatabaseConnection.java
  app/src/main/java/service/HttpService.java
  app/src/main/webapp/WEB-INF/account.jsp
  app/src/main/webapp/WEB-INF/index.jsp
  app/src/main/webapp/WEB-INF/jsps/accountPage.jsp
  app/src/main/webapp/WEB-INF/jsps/cart.jsp
  app/src/main/webapp/WEB-INF/jsps/categories.jsp
  app/src/main/webapp/WEB-INF/jsps/category.jsp
  app/src/main/webapp/WEB-INF/jsps/checkout.jsp
  app/src/main/webapp/WEB-INF/jsps/detailed.jsp
  app/src/main/webapp/WEB-INF/jsps/footer.jsp
  app/src/main/webapp/WEB-INF/jsps/header.jsp
  app/src/main/webapp/WEB-INF/jsps/loginPage.jsp
  app/src/main/webapp/WEB-INF/jsps/mainPage.jsp
  app/src/main/webapp/WEB-INF/jsps/managementPage.jsp
  app/src/main/webapp/WEB-INF/jsps/registerPage.jsp
  app/src/main/webapp/WEB-INF/jsps/testPage.jsp
  app/src/main/webapp/WEB-INF/login.jsp
  app/src/main/webapp/WEB-INF/management.jsp
  app/src/main/webapp/WEB-INF/register.jsp
  app/src/main/webapp/WEB-INF/test.jsp
  images/app.png
Labels: minor

#111 Update release.yml
  .github/workflows/release.yml
Labels: patch

#119 add image
  app/src/main/webapp/css/images/big/158514.jpg
Labels: minor

#120 .
  app/src/main/webapp/WEB-INF/jsps/loginPage.jsp
Labels: major
